### ISSUE TITLE
demande info

### ISSUE THREAD

**Issue by younes-dev** [AnnaDamm/RandomNumberCreator#1]
hey anna how are you doing ?
please i saw your comment in a issuse about git-hooks i would like to ask you if you could
work with it in php ?

**Comment by AnnaDamm** [comment]
Sorry I don't understand what you mean by "work with it"?

**Comment by younes-dev** [comment]
hey anna i meant did you implement the git-pre commit hooks in a php project ?
so to trigger the commit in case the code is not clean and dont respect the psr.
the checkers are phpCs , slinter ...

**Comment by AnnaDamm** [comment]
@younes-dev check out this gist: https://gist.github.com/AnnaDamm/2b24fc9d6d58a12730abe373914dbeb7

**Comment by younes-dev** [comment]
annn do you have linkedin where we could text please

**Comment by AnnaDamm** [comment]
No.
